/*
having  : summary  function  :  sum ,min ,max ,count(),avg

syntax :   select  col_name1 , col_name..... from table name  group by   having  (with aggregation finction) order by .... limit  

1 DISPLAY DEPARTMENT_ID WISE AVERAGE SALARY, DISPLAY THOSE ROWS WHICH HAS AVERAGE SALARY HIGHER THAN 10000
2 DISPLAY JOB_ID WISE NO. OF EMPLOYEES, DISPLAY THOSE ROWS WHICH HAS NO. OF EMPLOYEES UPTO 3
3 DISPLAY MANAGER_ID WISE TOTAL OF SALARY, DISPLAY ONLY THOSE ROWS WHICH HAS TOTAL OF SALARY HIGHER THAN 2000
4 DISPLAY DEPARTMENT WISE HIGHEST SALARY, DISPLAY ONLY THOSE ROWS WHICH HAS HIGHEST SALARY HIGHER THAN 10000
5 DISPLAY JOB WISE AVERAGE SALARY, DISPLAY ONLY THOSE ROWS WHICH HAS AVERAGE SALARY IN THE RANGE OF 8000 TO 12000
6 DISPLAY MANAGER WISE LOWEST SALARY , HIGHEST SALARY, DISPLAY ONLY THOSE ROWS WHICH HAS AVERAGE SALARY IN THE RANGE OF 6000 AND 9000
7 DISPLAY DEPARTMENT WISE , JOB WISE LOWEST SALARY , HIGHEST SALARY, DISPLAY ONLY THOSE ROWS WHICH HAS LOWEST SALARY LESS THAN 10000 OR HIGHEST SALARY HIGHER THAN 10000
8 DISPLAY HIRE YEAR WISE LOWEST SALARY, AVERAGE SALARY , HIGHEST SALARY DISPLAY ONLY THOSE ROWS WHICH HAS NO. OF EMPLOYEES HIRED 2 OR MORE IN YEAR
9 DISPLAY MANAGER_ID , COUNT OF EMPLOYEES REPORTING TO MGR, DISPLAY ONLY THOSE MGR INFO. TO WHOM 3 OR MORE EMPLOYEES REPORTING
10 DISPLAY JOB_ID , AVERAGE SALARY. DISPLAY ONLY THOSE JOB_ID WHOSE LOWEST SALARY IS BELOW 10000.
11 DISPLAY DEPARTMENT_ID , LOWEST SALARY , HIGHEST SALARY. DISPLAY ONLY THOSE DEPARTMENT_ID WHOSE LOWEST SALARY IS ABOVE 10000.
12 DISPLAY HIRE QUARTER WISE , NO. OF EMPLOYEES HIRED. DISPLAY ONLY QUARTER 2 AND 4 INFO.
13 DISPLAY HIRE MONTH WISE, HIGHEST SALARY , LOWEST SALARY , DIFFERENCE OF HIGHEST AND LOWEST SALARY. DISPLAY ONLY THOSE WHERE DIFFERENCE IS HIGHER THAN 4000.
14 SOLVE ABOVE QUESTION IN WHICH JOB_ID MUST BE DISPLAYED AS HEADING AND COUNT MUST BE DISPLAYED BELOW EACH JOB_ID

*/

-- 1 DISPLAY DEPARTMENT_ID WISE AVERAGE SALARY, DISPLAY THOSE ROWS WHICH HAS AVERAGE SALARY HIGHER THAN 10000

select department_id ,avg(salary) as avg_salary  
from employees 
group by  department_id 
having avg(salary) > 10000;

-- 2 DISPLAY JOB_ID WISE NO. OF EMPLOYEES, DISPLAY THOSE ROWS WHICH HAS NO. OF EMPLOYEES UPTO 3

select job_id ,count(*) as number_emp 
from employees 
group by  job_id 
having count(*) <= 3;
 
-- 3 DISPLAY MANAGER_ID WISE TOTAL OF SALARY, DISPLAY ONLY THOSE ROWS WHICH HAS TOTAL OF SALARY HIGHER THAN 2000
select manager_id ,sum(salary) as avg_salary  
from employees 
group by  manager_id 
having sum(salary) > 2000;

-- 4 DISPLAY DEPARTMENT WISE HIGHEST SALARY, DISPLAY ONLY THOSE ROWS WHICH HAS HIGHEST SALARY HIGHER THAN 10000

select department_id ,max(salary) as HIGHEST_SALARY
from employees 
group by department_id 
having max(salary) >10000;

-- 5 DISPLAY JOB WISE AVERAGE SALARY, DISPLAY ONLY THOSE ROWS WHICH HAS AVERAGE SALARY IN THE RANGE OF 8000 TO 12000

select job_id ,avg(salary) as avg_salary 
from employees 
group by  job_id 
having avg(salary) between 8000 and 12000;


-- 6 DISPLAY MANAGER WISE LOWEST SALARY , HIGHEST SALARY, DISPLAY ONLY THOSE ROWS WHICH HAS AVERAGE SALARY IN THE RANGE OF 6000 AND 9000

select manager_id ,
min(salary) as min_salary,
max(salary) as max_salary ,
avg(salary) as avg_salary
from employees 
group by manager_id 
having  avg(salary) >= 6000 and avg(salary) <= 9000;

/*7 DISPLAY DEPARTMENT WISE , JOB WISE LOWEST SALARY , HIGHEST SALARY, DISPLAY ONLY THOSE ROWS WHICH HAS LOWEST SALARY LESS THAN 
    10000 OR HIGHEST SALARY HIGHER THAN 10000
*/
select department_id ,job_id,max(salary) as HIGHEST_SALARY,
min(salary) as min_SALARY
from employees 
group by department_id ,job_id
having min(salary) <10000 or max(salary) > 10000;

/*8 DISPLAY HIRE YEAR WISE LOWEST SALARY, AVERAGE SALARY , HIGHEST SALARY DISPLAY ONLY THOSE ROWS WHICH HAS NO. OF EMPLOYEES 
    HIRED 2 OR MORE IN YEAR
*/ 
select year(hire_date) ,
min(salary) as min_salary,
max(salary) as max_salary ,
avg(salary) as avg_salary,
count(*) as number_emp 
from employees
group by year(hire_date)
having count(*) >=2 ; 

-- 9.DISPLAY MANAGER_ID , COUNT OF EMPLOYEES REPORTING TO MGR, DISPLAY ONLY THOSE MGR INFO. TO WHOM 3 OR MORE EMPLOYEES REPORTING

